twist_mux:
  ros__parameters:
    topics:
      joy:
        topic   : joy
        timeout : 0.5
        priority: 10
      keyboard:
        topic   : key_cmd_vel
        timeout : 0.5
        priority: 15
    locks:
      e_stop:
        topic   : e_stop
        timeout : 0.0
        priority: 255